accessing
caughtExceptions: anObject
	caughtExceptions value: anObject